name: PR - CI
on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'src/docs/**/*'
    branches: [ main ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build & Test
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1 on ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*

    - name: Setup .NET Core 5.0 on ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
        
    - name: Run
      run: |
        dotnet run --configuration Release --framework net6.0
        dotnet run --configuration Release --framework net5.0
        dotnet run --configuration Release --framework netcoreapp3.1
